### ISSUE TITLE
Error when http polling an endpoint that returns 204

### ISSUE THREAD

**Issue by sebastianslutzky** [logstash-plugins/logstash-input-http_poller#54]
I am using logstash's http_poller input to monitor several services. Each of them exposes an endpoint to this end.

One of them returns status code 204 (no content) and this results in an internal error of the http_poller plugin.

The rest of the endpoint return status code 200 and "All Is OK" raw text. They work fine.

The error is: 

`    /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/util/charset.rb:14:in `convert', /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json-2.1.4/lib/logstash/codecs/json.rb:38:in `decode', /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-http_poller-2.0.6/lib/logstash/inputs/http_poller.rb:166:in `handle_success', /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-http_poller-2.0.6/lib/logstash/inputs/http_poller.rb:158:in `request_async', org/jruby/RubyProc.java:281:in `call', /opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.5.5-java/lib/manticore/response.rb:250:in `handleResponse', Manticore$$Response_1062840788.gen:13:in `handleResponse', /opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.5.5-java/lib/manticore/response.rb:50:in `call', Manticore$$Response_1062840788.gen:13:in `call'`

and my configuration looks like this:

    input {
    	http_poller {
    		urls =>
    			{
    				myWebSite => "https://myWebsiteUrl:443/Monitor/Ping"
    			}
    	request_timeout => 30
    
    	# in seconds
    	interval => 30
    	tags => backend_healthcheck
    	metadata_target => http_poller_metadata
    	ssl_certificate_validation => false
    	}
    }
    filter {
    	if[http_poller_metadata]
    	{
    		mutate{
    			add_field =>{
    				"@target" => "%{http_poller_metadata[name]}"
    			}
    		}
    	}
    
    }
    output
    {
      elasticsearch { hosts => ["esServer:9200"]}
    }

**Comment by sebastianslutzky** [comment]
I expect no exception, ("http_request_failure" should be missing, tag _http_request_failure should not be present)"message" should be empty and http_poller_metadata.code should be 204
