### ISSUE TITLE
JRuby 9K failling job

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-input-http_poller#70]
https://travis-ci.org/logstash-plugins/logstash-input-http_poller/jobs/236450723

```
......................................F...............
Failures:
  1) LogStash::Inputs::HTTP_Poller instances normalizing a request spec URL specs auth with nested auth hash with auth enabled but no pass should raise an error
     Failure/Error: expect { normalized }.to raise_error(LogStash::ConfigurationError)
     
     NameError:
       uninitialized constant RSpec::Matchers::BuiltIn::RaiseError
       Did you mean?  RSpec::Matchers::BuiltIn::RaiseError
                      RangeError
     Shared Example Group: "auth" called from ./spec/inputs/http_poller_spec.rb:145
     # ./spec/inputs/http_poller_spec.rb:114:in `block in (root)'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in (root)'
Finished in 21 seconds (files took 4.22 seconds to load)
54 examples, 1 failure
Failed examples:
rspec ./spec/inputs/http_poller_spec.rb[1:1:3:2:3:1:1] # LogStash::Inputs::HTTP_Poller instances normalizing a request spec URL specs auth with nested auth hash with auth enabled but no pass should raise an error
Randomized with seed 24230

```

**Comment by ph** [comment]
closed by #72
